function importPartners() {
  let rows = [
  {"objectId":"zoYIVdCGLx", "name":"Nsafe Technologies LLP", "gstNumber":"", "status":"", "addressLine1":"C2-14, Rahul Park CHS, Near Utsav Hall", "addressLine2":" Shivteerth Nagar, Kothrud, Pune-411038", "area":"Kothrud", "city":"Pune", "state":"Maharashtra", "pincode":411038, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":2.0, "mobileNumber":7507507681, "annualTurnover":"", "serviceNames":"STP", "logoName":"", "website":"", "email":"nsafe.pune@gmail.com", "description":"One of the Company’s Director has more than 20 years of experience in the field of Sewage\nTreatment, Effluent Treatment. In last 20 years of his experience he had catered services to many esteemed clients.", "rankingScore":"", "rating":"", "estd":2020},
  {"objectId":"XoIFMvyI7q", "name":"Fire India Safety", "gstNumber":"", "status":"", "addressLine1":"Shop no. 30, 1st floor, PP Chamber, Bhagat Singh Road", "addressLine2":"Near KDMC Office, Dombivli East, 421201", "area":"Dombivli East", "city":"Mumbai", "state":"Maharashtra", "pincode":421201, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":15.0, "mobileNumber":9146479446, "annualTurnover":"", "serviceNames":"Fire System", "logoName":"", "website":"", "email":"fireindiasafety2016@gmail.com", "description":"We provide professional service in fire industry and having 15+ years of experience, any requirement related to Fire System Installation or maintanence kindly reach out", "rankingScore":"", "rating":"", "estd":2006},
  {"objectId":"TQ1m9UOFGl", "name":"Hi Tech Pest control", "gstNumber":"", "status":"", "addressLine1":"Yogita Apt 4th Floor,sai Nagar,kalyan East", "addressLine2":"", "area":"Kalyan East", "city":"Mumbai", "state":"Maharashtra", "pincode":421306, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":2.0, "mobileNumber":9004402351, "annualTurnover":"", "serviceNames":"Pest Control", "logoName":"", "website":"", "email":"hitechpestcontrol98@gmail.com", "description":"All types of Insect Proetction and Control, Service all over maharashtra", "rankingScore":"", "rating":"", "estd":2020},
  {"objectId":"4AA9CqqbGx", "name":"Zindus Infra ( I ) Pvt. Ltd.", "gstNumber":"", "status":"", "addressLine1":"29, Solitaire Industrial Premises Co-Soc Ltd. Plot No. TS-1", "addressLine2":"Opp Fire Brigade,Nr.Nandi Palace Hotel, Vicco Naka,Kalyan -Shil Rd, MIDC Phase -1,Dombivli- East\n", "area":"Dombivli East", "city":"Mumbai", "state":"Maharashtra", "pincode":421201, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":9.0, "mobileNumber":9819845747, "annualTurnover":"", "serviceNames":"Waterproofing", "logoName":"", "website":"www.zindus.in ", "email":"contact@zindus.in ", "description":"We are one of the professionally managed Civil & Structural Repair Contractor company. We commit ourselves to delight our clients by consistently meeting applicable client requirements and surpassing client expectation through Quality Construction, Timely completion and the most satisfying After Sales Service of Residential, Industrial, Commercial & Institutional Projects", "rankingScore":"", "rating":"", "estd":2013},
  {"objectId":"lOJbuoTzwK", "name":"Soryouth Renewable energy Pvt Ltd ", "gstNumber":"", "status":"", "addressLine1":"116-shubhlaxmi complex, shivaji maharaj chowk", "addressLine2":"Kalyan west", "area":"Kalyan West", "city":"Mumbai", "state":"Maharashtra", "pincode":421301, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":2.0, "mobileNumber":9967071218, "annualTurnover":"", "serviceNames":"Solar", "logoName":"", "website":"www.soryouth.com", "email":"soryouthenergy@gmail.com", "description":"Soryouth is a company dealing with the solar panel installation as solar power plant. \nWe are specialist in EPC, commissioning & installation of solar panel. \nWe try to give our customers the best quality in minimum rates. \nFounded in 2017, Soryouth is established as an EPC company for solar panel installations.\nWe do plan our setup or installation plans based on customers demand. \nWe do have team members having experience of 15 years in this profession.", "rankingScore":"", "rating":"", "estd":2020},
  {"objectId":"VhBM3aMo5w", "name":"Absolute Solutions & Services", "gstNumber":"", "status":"", "addressLine1":"Flat No. 504, Haripriya Society, Vasant Kamal Vihar", "addressLine2":"Warje, Pune, Maharashtra - 411058", "area":"Warje", "city":"Pune", "state":"Maharashtra", "pincode":411058, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":3.0, "mobileNumber":8446449946, "annualTurnover":"", "serviceNames":"VermiCulture", "logoName":"", "website":"", "email":"intouchwithass@gmail.com", "description":"We were established in the year of 2019. At the start, we started work in the field\nof Electrical wiring, Fabrication, Gearbox Repairing etc.\nFrom 2020, As a part of waste management sector we are ready to give Service to all\ntypes of OWC machines (Composting machine) as well. To serve in this field we have\nan experienced team who has experience more than 5 years in the same sector.", "rankingScore":"", "rating":"", "estd":2019},
  {"objectId":"8u71ZKlBFO", "name":"Gharefacility cleaning services ", "gstNumber":"", "status":"", "addressLine1":"At Post - maan, tal. mulshi, Dist.Pune Maharashtra India 411057", "addressLine2":"", "area":"Maan", "city":"Pune", "state":"Maharashtra", "pincode":411057, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":10.0, "mobileNumber":7758903049, "annualTurnover":"", "serviceNames":"Deep Cleaning", "logoName":"", "website":"https://cleaning-carpetcleaningservice.business.site/", "email":"Gharefacility@gmail.com", "description":"At Last...A Cleaning Company You Can Rely On.\nOur Expert Cleaners Will Do a Perfect Job - Every Time - Guaranteed.", "rankingScore":"", "rating":"", "estd":2011},
  {"objectId":"2ZPejICiQd", "name":"AV Enterprise", "gstNumber":"", "status":"", "addressLine1":"78/2 Gokul nagar atul nagar near warje mlavadi pune 58", "addressLine2":"", "area":"Warje", "city":"Pune", "state":"Maharashtra", "pincode":411058, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":2.0, "mobileNumber":9595008598, "annualTurnover":"", "serviceNames":"CCTV", "logoName":"", "website":"", "email":"avsarvice04@gmail.com", "description":"We are recognised maintenance company in CCTV Installation and Maintenance segment, we provide professional and reliable CCTV Installation, Maintenance and Repair services for Residentail, Corporate, Industrial segements", "rankingScore":"", "rating":"", "estd":2020},
  {"objectId":"NgNaMkoDuu", "name":"Shivraj Tank Cleaner Services", "gstNumber":"", "status":"", "addressLine1":"Moraya Colony, Chinchwadnagar, Walhekarwadi Road", "addressLine2":"Chinchwad", "area":"Chinchwad", "city":"Pune", "state":"Maharashtra", "pincode":411033, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":6.0, "mobileNumber":9766255202, "annualTurnover":"", "serviceNames":"Tank Cleaning", "logoName":"", "website":"", "email":"sureshbhandari304@gmail.com", "description":"Water Tank Cleaning services at your doorstep, we use modern instruments to perform the service with best quality", "rankingScore":"", "rating":"", "estd":2016},
  {"objectId":"mXAFQ4XB2D", "name":"Anas Fabrication Works", "gstNumber":"", "status":"", "addressLine1":"Warje Canal Road, Morya hightech Building, Warje, Pune", "addressLine2":"", "area":"Warje", "city":"Pune", "state":"Maharashtra", "pincode":411058, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":3.0, "mobileNumber":8356020337, "annualTurnover":"", "serviceNames":"Fabrication", "logoName":"", "website":"", "email":"mohamadhusen944@gmail.com", "description":"All kind of Fabrication work with best quality and in budget pricing available", "rankingScore":"", "rating":"", "estd":2019},
  {"objectId":"9yVyhIojNj", "name":"GM Enterprises ", "gstNumber":"", "status":"", "addressLine1":"Shop no. 5, Sulai Complex , Opp. H. V. Desai hospital", "addressLine2":"Anand Nagar, Mohammadwadi, pune-411060", "area":"Mohammadwadi", "city":"Pune", "state":"Maharashtra", "pincode":411060, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":2.0, "mobileNumber":8830417142, "annualTurnover":"", "serviceNames":"Solar", "logoName":"", "website":"", "email":"gmenterprises9696@gmail.com", "description":"Get your propertly solar ready today with complete information and guidance from our technician and complete end to end project execution with professional service and reporting", "rankingScore":"", "rating":"", "estd":2020},
  {"objectId":"DWAZRyzyIa", "name":"Pritam Hydrotech Engineers", "gstNumber":"", "status":"", "addressLine1":"Sr.No. 63/4 Sonawane Wasti Tathawade Tal. Mulshi, Dist.Pune 411011", "addressLine2":"", "area":"Mulshi", "city":"Pune", "state":"Maharashtra", "pincode":411011, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":3.0, "mobileNumber":9371668605, "annualTurnover":"", "serviceNames":"STP,WTP", "logoName":"", "website":"", "email":"pritamhydrotechengineers@gmail.com", "description":"We provide services related to Sewage Treatment Plant (STP) and Water Treatment Plant (WTP) for complete installation or maintenance or repair\nOur technician make sure to provide complete report on the work", "rankingScore":"", "rating":"", "estd":2019},
  {"objectId":"c1kTdPpEUs", "name":"Authentic Netting and Spikes Pvt Ltd", "gstNumber":"", "status":"", "addressLine1":"B-202,Sai Prasad Apartment,Behind RMD Sinhagad College,Warje,Pune-411058.", "addressLine2":"", "area":"Warje", "city":"Pune", "state":"Maharashtra", "pincode":411058, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":3.0, "mobileNumber":7276603344, "annualTurnover":"", "serviceNames":"Bird Net", "logoName":"", "website":"www.authenticnetting.com", "email":"info@authenticnetting.com", "description":"Authentic Nettings bird netting service can be used by everyone irrespective of the size of the premises. Our pigeon protection service is totally customizable and can be implemented on every possible premise. We also provide balcony netting services to safeguard your plantation. Apart from this, we do protect building entrance, dome structures, building roof, parapet walls, building corridor, Ac roof, Lamppost, from bird droppings and nesting. Bird littering, nesting materials, and filthy smell are unattractive features for any home. A corridor covered with bird droppings and a home with a filthy smell may send a message of your careless behavior to the visitors. We provide one of the best residential bird netting services in Pune.", "rankingScore":"", "rating":"", "estd":2019},
  {"objectId":"FXUyzOxPLZ", "name":"Agni Fire Fighting Services", "gstNumber":"", "status":"", "addressLine1":"G004, B5 Nav Annapurna Arti CHS, Annapurna Nagar, Adharwadi, Kalyan West 421301", "addressLine2":"", "area":"Kalyan West", "city":"Mumbai", "state":"Maharashtra", "pincode":421301, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":7.0, "mobileNumber":9881888422, "annualTurnover":"", "serviceNames":"Fire System", "logoName":"", "website":"http://www.agnifire.in/", "email":"agnifirefightingservices@gmail.com", "description":"We are one of the leading company located at Kalyan-Dombivli Municipal Corporation, Maharashtra. We Agni Fire Firefighting Services help you understand fire risks and offer reliable fire safety fire extinguishers and solutions to safeguard everything you love. With the goal of empowering lives to safety, We install Fire fighting systems as well as maintain installed systems. We have satisfied client-list of 150+ societies also we have done 50+ New Projects", "rankingScore":"", "rating":"", "estd":2015},
  {"objectId":"qZsU9Eo4uF", "name":"Balaji Waterproofing", "gstNumber":"", "status":"", "addressLine1":"Jai Bhavani Nagar, Paund Road , Kothrud,Pune", "addressLine2":"", "area":"Kothrud", "city":"Pune", "state":"Maharashtra", "pincode":411038, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":4.0, "mobileNumber":9588469859, "annualTurnover":"", "serviceNames":"Waterproofing", "logoName":"", "website":"", "email":"balajichavanj28@gmail.com", "description":"We provide water lekage detetction and waterproofing solution services for Homes, Residential, Commercial and Industrial segments\n", "rankingScore":"", "rating":"", "estd":2018},
  {"objectId":"mFElmFjd9t", "name":"Sanjeevani Services", "gstNumber":"", "status":"", "addressLine1":"Parshuram Plaza, Shop 12, Opp. Kashish International Hotel", "addressLine2":"Shree Malang Road, Kalyan East, Kalyan - 421301.", "area":"Kalyan East", "city":"Mumbai", "state":"Maharashtra", "pincode":421301, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":10.0, "mobileNumber":9930742021, "annualTurnover":"", "serviceNames":"Tank Cleaning", "logoName":"", "website":"", "email":"sanjeevaniservices1@gmail.com", "description":"Water Tank Cleaning services for Residential, Commercial and Industrial segments\nFor more details kindly contact", "rankingScore":"", "rating":"", "estd":2012},
  {"objectId":"CAImeFzp0L", "name":"Ideal Elevator and Escalator Pvt. Ltd.", "gstNumber":"", "status":"", "addressLine1":"Office no 5, Sr No.1002, City Plaza Building, Laxmi Road, Pune 411002", "addressLine2":"", "area":"Laxmi Road", "city":"Pune", "state":"Maharashtra", "pincode":411002, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":7.0, "mobileNumber":9372336558, "annualTurnover":"", "serviceNames":"Lift", "logoName":"", "website":"www.idealelevator.in", "email":"ieeplindia@outlook.com", "description":"We, Ideal Elevators Co located in Vishrantwadi, Pune, Maharashtra provide all types of elevator repair, maintenance, installation and modification services. Our skilled and expert technicians always strive hard to serve our client's requirements. Client satisfaction is our ultimate goal. We provide our services to all corporate, residential buildings, government offices, malls, hospitals, schools, colleges, etc. We take pride in serving our esteemed clients", "rankingScore":"", "rating":"", "estd":2015},
  {"objectId":"3Ze9f8Wxz4", "name":"Tuljabhawani Enterprises ", "gstNumber":"", "status":"", "addressLine1":"SR No 39 /31 Matoshri Colony Gujar nagar Thergaon pune -411033", "addressLine2":"", "area":"Thergaon", "city":"Pune", "state":"Maharashtra", "pincode":411033, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":10.0, "mobileNumber":9881848475, "annualTurnover":"", "serviceNames":"Waterproofing", "logoName":"", "website":"", "email":"selestuljabhawanienterprises@gmail.com", "description":"Tuljabhawani Enterprises Establish in the year of 2012, Tuljabhawani Enterprises is one of\nthe Leading Service Provider of Floor Coating.\nWe are Providing Services like Epoxy Flooring, Antistatic Floorings, Antiskid\nFloorings, PU Coatings, PU Floorings, High Voltage Floorings, Hygiene Wall Coatings, 3D\nFloorings, PU Wall Coatings, and Water Proofing. These services we are offering in market\nat reasonable rates. These offered services are highly qualitative, quiatative, customer\noriented, durable and fast dedicated approach.\n\n15-20 employee having more than 8 Years experience in concern field. Our team\ncomprises of the strong set up in the country with maximum strength in all India Markets.", "rankingScore":"", "rating":"", "estd":2012},
  {"objectId":"p0Wnd4nfPL", "name":"Neuproel Solutions Pvt. Ltd.", "gstNumber":"", "status":"", "addressLine1":"Office No. 3, Sakhare Estate, Near Courtyard Marriot Hotel", "addressLine2":"Hinjewadi-Wakad Road, Wakad, Pune-411057", "area":"Wakad", "city":"Pune", "state":"Maharashtra", "pincode":411057, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":4.0, "mobileNumber":9764426602, "annualTurnover":"", "serviceNames":"CCTV", "logoName":"", "website":"www.neuproel.com", "email":"nikhil.ekhande@neuproel.com", "description":"Neuproel Solutions Provide Computer Networking, Security Surveillance, Access Control System, Audio Visual System, Public Address(PA) System, Wireless Device, Accesss Point Services, CCTV Service.\nWe are committed to the basic principles of professionalism, quality workmanship, fast response and above all complete customer satisfaction.", "rankingScore":"", "rating":"", "estd":2018},
  {"objectId":"yifBpEmSLb", "name":"Atoneklick ", "gstNumber":"", "status":"", "addressLine1":"Yograj apartment office no 6 floor no 2 balewadi phata baner pune 411045", "addressLine2":"", "area":"Baner", "city":"Pune", "state":"Maharashtra", "pincode":411045, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":5.0, "mobileNumber":7020600478, "annualTurnover":"", "serviceNames":"Rent  Agreement", "logoName":"", "website":"https://maharashtrarentagreement.com/home", "email":"yogeshpanpaliya@gmail.com", "description":"We Are A Self-Service Platform That Acts As An Intermediary BetweenEnd Customers And E-RentalAgreement Registration Agents. The Idea Is To Reduce The Cost Burden On The End Customer And Simplify Online Rental Agreement Registration.\nWe have worked as an online registration service provider with over 5 years of experience, hence we know the process in-depth. After understanding the pain-points of the customers and the vendors, we came up with the idea of a self-service portal for e-registration of rental agreement.\nWe have a team of 5 professional advisors and we have been working in Pune from 2002. We have a huge network of trusted and reliable partners across India.", "rankingScore":"", "rating":"", "estd":2017},
  {"objectId":"IMx8PdvPSs", "name":"Shree Water Tech", "gstNumber":"", "status":"", "addressLine1":"Office No.5, Bajirao Classic Building, Near Pavana Sahakari Bank, Thergaon, Pune 411033", "addressLine2":"", "area":"Thergaon", "city":"Pune", "state":"Maharashtra", "pincode":411033, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":5.0, "mobileNumber":9579738516, "annualTurnover":"", "serviceNames":"STP,WTP", "logoName":"", "website":"www.shreewatertech.com", "email":"Shreewatertech@gmail.com", "description":"Shree Water Tech formed in 2014 focusing Water and Waste water treatment needs not only for the end customers. We have more than 150 installations across India of different kinds, are designed and integrated by us. We use our wide range of processes with an integrated approach to deliver total solutions for every market - household, institutional, commercial and industrial in India. Our Comprehensive and personalized approach driving us to meet customer needs totally, offering end benefit conveniently and economically, with single point responsibility.\n\nWe have sufficient expertise in Pre-treatment, process water/liquid treatment, and waste water treatment, water recycle and product recovery using various physical-chemical processes for settling, clarification, filtration, and disinfection, membrane and ion exchange technology for effective liquid – Solid Separation technique", "rankingScore":"", "rating":"", "estd":2017},
  {"objectId":"UEISoFdhfc", "name":"Yash Services ", "gstNumber":"", "status":"", "addressLine1":"Kothrud", "addressLine2":"", "area":"Kothrud", "city":"Pune", "state":"Maharashtra", "pincode":411038, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":2.0, "mobileNumber":9823111527, "annualTurnover":"", "serviceNames":"Tank Cleaning", "logoName":"", "website":"", "email":"yashservices789@gmail.com", "description":"All Type of water tank cleaning, we use moden technology driven approach and machinery ", "rankingScore":"", "rating":"", "estd":2020},
  {"objectId":"kCYpcbDfWf", "name":"Dolphin Guards & Allied Services", "gstNumber":"", "status":"", "addressLine1":"Geet Siddhi S.NO 11, Moshi Pradhikaran Bhorhadewadi Near CNG pump office No 01-02 4th Floor 412105", "addressLine2":"", "area":"Moshi", "city":"Pune", "state":"Maharashtra", "pincode":412105, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":17.0, "mobileNumber":9921178585, "annualTurnover":"", "serviceNames":"Security", "logoName":"", "website":"https://www.dolphinguardss.com/", "email":"info@dolphinguardss.com", "description":"Group set up with the aim to provide a cost-effective system that incorporates the various needs of commercial, industrial and residential premises. DGAS is the culmination of prudence and research by a group of professional experts familiar with the field of property management. Dolphin Guardss & Allied Services Pvt Ltd provides security services. We address specific issues of each client and design customized solutions for them.", "rankingScore":"", "rating":"", "estd":2005},
  {"objectId":"k3xq8e8Tii", "name":"Swimwell Frp Pool Pvt Ltd", "gstNumber":"", "status":"", "addressLine1":"5 & 6, City Arcade, Near Arif Compound,\nPanvel Mumbra Road, Mumbra-Dahisar Village, Thane 400612", "addressLine2":"", "area":"Thane", "city":"Mumbai", "state":"Maharashtra", "pincode":400612, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":5.0, "mobileNumber":8652632703, "annualTurnover":"", "serviceNames":"Swimming Pool", "logoName":"", "website":"swimwell.co.in", "email":"zubeda@swimwell.co.in ", "description":"Appreciated in the market for fabrication and installation of a complete range of pool and spa products, we have achieved proficiency in the field. Our Pool Products are developed industrially to meet international standards. Our quality experts conduct stringent tests to ensure the launch quality of our products\n\nOur high-quality product range has helped us gain several satisfied and loyal clients in the competitive Swimming Pool Construction market. The advanced management concepts, best techniques and post-sales services that we offer have created a favourable image in the eyes of our clients", "rankingScore":"", "rating":"", "estd":2017},
  {"objectId":"hch9WINrap", "name":"Kilo Security Services", "gstNumber":"", "status":"", "addressLine1":"102, Sahayog Apartments, Sus Road, Baner, Pune", "addressLine2":"", "area":"Baner", "city":"Pune", "state":"Maharashtra", "pincode":411045, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":6.0, "mobileNumber":7769001444, "annualTurnover":"", "serviceNames":"Security", "logoName":"", "website":"www.kiloservices.in", "email":"connect@kiloservices.in", "description":"Run by Team of Ex Army Officers and Dedicated to Service and Client Satisfaction\nOwner is Indian Army Retired Officer with 30 years in National Security and 14 years in Public Security Domain. ", "rankingScore":"", "rating":"", "estd":2016},
  {"objectId":"G0zslDszWl", "name":"Cleanfield Facility Management Pvt. Ltd", "gstNumber":"", "status":"", "addressLine1":"At S.No-141, Ram Nagar Near kranti Mitra mandal Yerwada Pune - 411006", "addressLine2":"", "area":"Yerwada", "city":"Pune", "state":"Maharashtra", "pincode":411006, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":2.0, "mobileNumber":8805982159, "annualTurnover":"", "serviceNames":"Housekeeping", "logoName":"", "website":"", "email":"deepak.akhade@cleanfieldfacility.com", "description":"Deepak Akhade owner of the agnecy have 10 yers of experience for same field , Also worked for hotel like, Taj,Hyatt and Radisson hotel as Facilities manager ", "rankingScore":"", "rating":"", "estd":2020},
  {"objectId":"HBx7cIIuyX", "name":"Society Plus", "gstNumber":"", "status":"", "addressLine1":"Office no 145, 3rd floor, Prestiage Point, Off Bajirao Road, Opp. Chinchechi Talim, 283 Shukrawar Peth, pune 411002 ", "addressLine2":"", "area":"Shukrawar Peth", "city":"Pune", "state":"Maharashtra", "pincode":411002, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":33.0, "mobileNumber":9545332104, "annualTurnover":"", "serviceNames":"Legal Solution, Accounting Service", "logoName":"", "website":"www.societyplus.co.in", "email":"info@societyplus.co.in", "description":"Society Plus brings the knowhow for the formation, management, and maintenance of cooperative housing societies. We are the unquestioned market leader, providing innovative and pragmatic solutions to clients. For more than 31 years, we have worked closely with renowned housing societies and established builders in Pune to provide a suite of best-in-class services. Trusted by a clientele including over 151+ Builders and 1,500+ Societies, we are the only end-to-end solution provider for all your society needs.\n\nOur services are Legal Solution, Accounting Audits, Statutary Complainces, Society Management Consultany Services, Redevelopment, Society Registeration, Conveyance Deed and many more", "rankingScore":"", "rating":"", "estd":1989},
  {"objectId":"zepZBFzPK6", "name":"Technical security", "gstNumber":"", "status":"", "addressLine1":"5, 22/01/01, Mundhwa - Kharadi Rd, Raghoba Patil Nagar, Thite Nagar, Kharadi, Pune, Maharashtra 411014", "addressLine2":"", "area":"Kharadi", "city":"Pune", "state":"Maharashtra", "pincode":411014, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":4.0, "mobileNumber":8605208691, "annualTurnover":"", "serviceNames":"CCTV", "logoName":"", "website":"", "email":"markads135@gmail.com", "description":"We are expericned and having expertise in CCTV Camera Installations and AMC, Biometric Attendance System, Video Door Phone, Shutter Alarm System, All type of CCTV Camera brands are available", "rankingScore":"", "rating":"", "estd":2018},
  {"objectId":"FE8K4APDJQ", "name":"1 st Alert Security Service", "gstNumber":"", "status":"", "addressLine1":"Atul Nagar b3 building ground floor lg 2 Mohammed Wadi road Pune 411060", "addressLine2":"", "area":"Mohammadwadi", "city":"Pune", "state":"Maharashtra", "pincode":411060, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":7.0, "mobileNumber":9022076674, "annualTurnover":"", "serviceNames":"Security", "logoName":"", "website":"", "email":"1st.alert11@gmail.com", "description":"1st alert is a leader in facility management, Its established Ex servicemen organization and also registered with PASARA provide high class security service in Maharashtra. ", "rankingScore":"", "rating":"", "estd":2015},
  {"objectId":"PmFHR7M3KA", "name":"Airfine Energy Pvt Ltd", "gstNumber":"", "status":"", "addressLine1":"302/5, Sarvoday Garden, Near Bhanu Sagar, Kalyan West, Thane, Maharashtra - 421301", "addressLine2":"", "area":"Kalyan West", "city":"Mumbai", "state":"Maharashtra", "pincode":421301, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":1.0, "mobileNumber":9892375010, "annualTurnover":"", "serviceNames":"Solar", "logoName":"", "website":"www.airfineindia.com", "email":"chetan@airfineindia.com", "description":"AIRFINE ENERGY has strong network of Manufacturers, Service providers and Domain Experts to assure its customers  guaranteed quality, timely delivery and affordable rates for their Solar Energy Needs! ", "rankingScore":"", "rating":"", "estd":2022},
  {"objectId":"bqAHCWrmss", "name":"Rise and Shine Facility Services", "gstNumber":"", "status":"", "addressLine1":"Jagdamba Housing Society, Somnath Nagar,Vadgaon Sheri , Pune - 411014", "addressLine2":"", "area":"Vadgaon Sheri", "city":"Pune", "state":"Maharashtra", "pincode":411014, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":2.0, "mobileNumber":8087893149, "annualTurnover":"", "serviceNames":"Housekeeping", "logoName":"", "website":"", "email":"riseandshine.facilityservices@gmail.com", "description":"We are offering a proposal that is designed towards maintaining your premises as per ‘World Class Standards’. Our proposal is primarily defined by the usage of a combination of ‘Men-Machine-cleaning Agents (chemicals) & cleaning processes’ that would result in the achievement of the ultimate objective", "rankingScore":"", "rating":"", "estd":2020},
  {"objectId":"v3TWaTaw1z", "name":"Greenway Fire Solution", "gstNumber":"", "status":"", "addressLine1":"11/1, 4, Omkar bunglow, Dyanesh society, Warje malwadi, pune 411058", "addressLine2":"", "area":"Warje", "city":"Pune", "state":"Maharashtra", "pincode":411058, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":1.0, "mobileNumber":9766184702, "annualTurnover":"", "serviceNames":"Fire System", "logoName":"", "website":"www.Greenwayfiresolution.com", "email":"greenwayfiresolution@gmail.com", "description":"Greenway Fire Solution has been established as fire safety industries to ensure complete fire safety services and provide best possible services. Our customer is our first priority so we provide free on time delivery to the plant and industries. We have grown out of the need of ensuring safety and professional guidance to the public for safer and proper usage of all fire and industrial equipment.", "rankingScore":"", "rating":"", "estd":2022},
  {"objectId":"y7DxfVL6x6", "name":"S M Facility ", "gstNumber":"", "status":"", "addressLine1":"Shiv Sai aprtment, behind shyadari hospital, Vanaj Company, 411038", "addressLine2":"", "area":"Kothrud", "city":"Pune", "state":"Maharashtra", "pincode":411038, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":4.0, "mobileNumber":9011677275, "annualTurnover":"", "serviceNames":"Housekeeping, Gardening, Tank Cleaning, STP", "logoName":"", "website":"", "email":"smfacilities2019@gmail.com", "description":"SM Facilities providing best services in Housekeeping, Gardedening & STP-WTP technical services all over Pune with all technical support manpower as well", "rankingScore":"", "rating":"", "estd":2018},
  {"objectId":"YQEooHtOby", "name":"Pune Fire Safety And CCTV ", "gstNumber":"", "status":"", "addressLine1":"Shop No.8, Ravikiran Apartment, Wadmukhwadi, Pune 412105", "addressLine2":"", "area":"Wadmukhwadi", "city":"Pune", "state":"Maharashtra", "pincode":412105, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":2.0, "mobileNumber":9766576119, "annualTurnover":"", "serviceNames":"Fire System, CCTV", "logoName":"", "website":"", "email":"sales@punefire.com", "description":"Pune Fire Safety & Electronic Security System with the team having more than 7 years of\nexperience in fire safety and CCTV, PUNE FIRE SAFETY & CCTV is one of the leading companies in Fire safety Products Affiliated to\nIS 15683 AND IS 5290. We aim to provide quality services with cutting-edge solutions to the clients.", "rankingScore":"", "rating":"", "estd":2020},
  {"objectId":"KkgTNlPeVQ", "name":"Shree Renuka Fabrication ", "gstNumber":"", "status":"", "addressLine1":"Sai Krupa Apartments ,Sinhgad Road, Vadgaon Bk , Pune", "addressLine2":"", "area":"Vadgaon", "city":"Pune", "state":"Maharashtra", "pincode":411041, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":2.0, "mobileNumber":9595971561, "annualTurnover":"", "serviceNames":"Fabrication", "logoName":"", "website":"", "email":"sp60886@gmail.com", "description":"All type of fabrication work at best prices, contact to know more details", "rankingScore":"", "rating":"", "estd":2020},
  {"objectId":"AlLYnSgq6O", "name":"Akash Electrician And Plumber", "gstNumber":"", "status":"", "addressLine1":"Near 24K , Sereno chowk , opp athshree society, Pan Card club road , Baner , Pune", "addressLine2":"", "area":"Baner", "city":"Pune", "state":"Maharashtra", "pincode":411045, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":1.0, "mobileNumber":9834294942, "annualTurnover":"", "serviceNames":"Electrical Work, Plumbing Work", "logoName":"", "website":"", "email":"aakvip007@gmail.com", "description":"All type electrical and plumbing work, we provide professional service at your doorstep", "rankingScore":"", "rating":"", "estd":2021},
  {"objectId":"KNQjrf27YF", "name":"Swara Glass And Fabrication ", "gstNumber":"", "status":"", "addressLine1":"Shrinivas Vihar,Pari Company Road,Manaji Nagar,Narhe", "addressLine2":"", "area":"Narhe", "city":"Pune", "state":"Maharashtra", "pincode":411041, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":4.0, "mobileNumber":8605736458, "annualTurnover":"", "serviceNames":"Fabrication", "logoName":"", "website":"", "email":"somnathshinde74786@gmail.com", "description":"We provide Glass and Fabrication work required for residential, corporate and industrial segments, contact to know more details", "rankingScore":"", "rating":"", "estd":2018},
  {"objectId":"DjQbDWeU92", "name":"A S K Security And Management Services Pvt Ltd ", "gstNumber":"", "status":"", "addressLine1":"Raj Chaya Apartment, Near Sai Hospital, Sane Chowk, Akurdi Chikhli Road Chinchwad ", "addressLine2":"", "area":"Akurdi", "city":"Pune", "state":"Maharashtra", "pincode":411035, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":7.0, "mobileNumber":7745821155, "annualTurnover":"", "serviceNames":"Security", "logoName":"", "website":"", "email":"ask.security@icloud.com", "description":"ASK Security And Management Services private Limited is Licensed with P.S.A.R. Act 2005 (Private Security Agency Regulation Act 2005) in States Maharashtra, Empanelled with Directorate General of Resettlement, Ministry of Defense and is registered with Government of India under Companies Act is managed by professionals from various fields. We have 16 years experience in this profession.", "rankingScore":"", "rating":"", "estd":2015},
  {"objectId":"t9GWrelN5e", "name":"Paradise Fire & Security Pvt Ltd ", "gstNumber":"", "status":"", "addressLine1":"103, Blue Berry Plaza, Above Axis Bank AmbedkarChawk, DY Patil College Rd, Ravet,Pimpri-Chinchwad, Pune Maharashtra 411033", "addressLine2":"", "area":"Ravet", "city":"Pune", "state":"Maharashtra", "pincode":411033, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":7.0, "mobileNumber":8975622209, "annualTurnover":"", "serviceNames":"CCTV", "logoName":"", "website":"www.paradisefire.in", "email":"sales@paradisefire.in", "description":"At Paradise fire & security, we offer fire extinguisher refilling and maintenance service 365 days round the clock. We also conduct fire safety inspection, Fire Awareness training & fire drills. Our vision is to provide total fire & safety solutions to the customer to ensure complete protection of life & property. We are committed to respond to your specific needs related to fire safety and continual improvement in our training programs", "rankingScore":"", "rating":"", "estd":2015},
  {"objectId":"O203DoipvG", "name":"Marshal Industrial Services ", "gstNumber":"", "status":"", "addressLine1":"Balaji Apartment Vidhate Wasti DP Road Aundh Pune ", "addressLine2":"", "area":"Aundh", "city":"Pune", "state":"Maharashtra", "pincode":411007, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":5.0, "mobileNumber":8801235050, "annualTurnover":"", "serviceNames":"Security, Housekeeping", "logoName":"", "website":"www.misgrous.in", "email":"misgrouppune@gmail.com", "description":"We provide all types of Security, House Keeping and facility services ", "rankingScore":"", "rating":"", "estd":2017},
  {"objectId":"btytOZ6ihM", "name":"Ekdant Equipments Pvt Ltd", "gstNumber":"", "status":"", "addressLine1":"RH. No. A4, Golden Orchid, S.No.11, P.No.136, Chikhali Pradhikaran, Chinchwad, Pune-411019", "addressLine2":"", "area":"Chinchwad", "city":"Pune", "state":"Maharashtra", "pincode":411019, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":9.0, "mobileNumber":9960463364, "annualTurnover":"", "serviceNames":"STP", "logoName":"", "website":"www.eepl.co", "email":"dk@eepl.co", "description":"EEPL is a company specialized to provide the solutions in the field of Dust & Fume Extractions, Lawn & Garden Solutions, All Type of Cleaning equipments  & CNC rotary solutions for each and every Organization, Industry, Institutes & Commercial places\n\nWith more than 10  years of experience in the above fields and the top competency of the technical staff, sales and post-sales, EEPL Solutions has consistently innovated, enhanced, and added its range of products by customizing each item according to the need and client requirements", "rankingScore":"", "rating":"", "estd":2013},
  {"objectId":"tqFSZXieQL", "name":"Tech Logical Solutions", "gstNumber":"", "status":"", "addressLine1":"Office No 130, H Wing, Jai Ganesh Samrajya, Bhosari MIDC, Pimpri Chinchwad, Pune -411039.", "addressLine2":"", "area":"Bhosari", "city":"Pune", "state":"Maharashtra", "pincode":411039, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":7.0, "mobileNumber":9623413953, "annualTurnover":"", "serviceNames":"CCTV", "logoName":"", "website":"www.tlsindia.co.in", "email":"ceo.tlsindia@gmail.com", "description":"Established in 1990, We Tech Logical Solutions are a highly famous organization of the industry involved in wholesaler, trader and service Provider a broad assortment of best quality Time Attendance System, CCTV Camera, Video Door Phones, Fire Alarm Monitoring Services etc", "rankingScore":"", "rating":"", "estd":2015},
  {"objectId":"LjZ3wYpA8Z", "name":"Voltstar Solar", "gstNumber":"", "status":"", "addressLine1":"Runwal Srushti, Baner, Pune", "addressLine2":"", "area":"Baner", "city":"Pune", "state":"Maharashtra", "pincode":411045, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":3.0, "mobileNumber":7387788778, "annualTurnover":"", "serviceNames":"Solar", "logoName":"", "website":"www.voltstarsolar.com", "email":"voltstarsolar@gmail.com", "description":"Voltstar Solar is leading Solar Rooftop, EPC Company based in PUNE, Maharashtra, INDIA. Founded by industry experts company is pioneered in delivering efficient, customized and quality renewable energy solutions that best meet needs and offer reliable power with exponential returns to our customer", "rankingScore":"", "rating":"", "estd":2019},
  {"objectId":"d2AqooFCLA", "name":"Fitness Tech", "gstNumber":"", "status":"", "addressLine1":"13, tadiwala road sanmyak nagar lane no 11, Pune - 411001", "addressLine2":"", "area":"Yerwada", "city":"Pune", "state":"Maharashtra", "pincode":411001, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":12.0, "mobileNumber":9764977231, "annualTurnover":"", "serviceNames":"Gym", "logoName":"", "website":"fitnesstechindia.in", "email":"fitnesstechindia@gmail.com", "description":"We provide Gym related services like Gym machine Installation, Maintenance and Repair\nWe have about 13+ years of experience in this field and diverse set of clients", "rankingScore":"", "rating":"", "estd":2009},
  {"objectId":"9ofe5h9vAo", "name":"MAVI Green Energy", "gstNumber":"", "status":"", "addressLine1":"Stargaze B1309, Near Windmill Village, Bavdhan, Pune 411021", "addressLine2":"", "area":"Bavdhan", "city":"Pune", "state":"Maharashtra", "pincode":411021, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":1.0, "mobileNumber":8530203277, "annualTurnover":"", "serviceNames":"EV", "logoName":"", "website":"https://www.mavigreenenergy.com/", "email":"info@mavigreenenergy.com", "description":"We are here to build as sustainable future by providing end to end flexible Electrical Vehicle (EV) Charging Solutions", "rankingScore":"", "rating":"", "estd":2021},
  {"objectId":"wJpSM97DPh", "name":"Green Earth Water Solutions", "gstNumber":"", "status":"", "addressLine1":"SunEmpire phase1 Building A2Flat #101\nSuncity Road Anand Nagar off Sinhgad Road Pune 411051", "addressLine2":"", "area":"Sinhgad Road", "city":"Pune", "state":"Maharashtra", "pincode":411051, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":6.0, "mobileNumber":8080036560, "annualTurnover":"", "serviceNames":"Water Sensor and Automation", "logoName":"", "website":"", "email":"sanjay_688@rediffmail.com", "description":"We provides services for all kind of pump works and waster sensor automation, having more than 5 years of experience in the industrry", "rankingScore":"", "rating":"", "estd":2016},
  {"objectId":"06sMtG2Wuf", "name":"Solsum Energy Solutions", "gstNumber":"", "status":"", "addressLine1":"12/1, Anand Nagar, Old Sangavi, Pune-411027", "addressLine2":"", "area":"Sangavi", "city":"Pune", "state":"Maharashtra", "pincode":411027, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":3.0, "mobileNumber":9011078250, "annualTurnover":"", "serviceNames":"Solar", "logoName":"", "website":"https://solsumenergy.in/", "email":"info@solsumenergy.in", "description":"Solsum Energy Solutions is a perfect solar solution company with a vision to spread solar power in India. Solsum Energy Solutions was established in 2014 and provides comprehensive range of products and services ranging from residential households to corporate and industrial solar set up.", "rankingScore":"", "rating":"", "estd":2019},
  {"objectId":"VLlDLrklf9", "name":"Shree Enterprises", "gstNumber":"", "status":"", "addressLine1":"office no 16, Mahtoba Complex, Ananta Nagar, Hinjewadi, Pune - 411057", "addressLine2":"", "area":"Hinjewadi", "city":"Pune", "state":"Maharashtra", "pincode":411057, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":2.0, "mobileNumber":8484845503, "annualTurnover":"", "serviceNames":"Housekeeping", "logoName":"", "website":"", "email":"shreeenterprises743@gmail.com", "description":"We provide Professional Housekeeping and Cleaning related work, kindly contact and know more details", "rankingScore":"", "rating":"", "estd":2020},
  {"objectId":"HCVXhcdSHn", "name":"Atlantis Pools India", "gstNumber":"", "status":"", "addressLine1":"1 Mohan Kunj J P Road East, Naigaon, Dadar, Mumbai, Maharashtra 400014", "addressLine2":"", "area":"Dadar", "city":"Mumbai", "state":"Maharashtra", "pincode":400014, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":5.0, "mobileNumber":7721888666, "annualTurnover":"", "serviceNames":"Swimming Pool", "logoName":"", "website":"", "email":"atlantispoolsolutions@gmail.com", "description":"If you need service related to Swimming Pool then Atlantis pool solution is the right place, we provide Swimming Pool Miantenance, Repair and Installation, Life Guard or Training type of services", "rankingScore":"", "rating":"", "estd":2017},
  {"objectId":"vmPn86J7qo", "name":"JD Enerbiz Pvt Ltd", "gstNumber":"", "status":"", "addressLine1":"113/1, Siddhivinayak Residency, Tulsivihar, Asangaon(E)421601", "addressLine2":"", "area":"Asangaon", "city":"Mumbai", "state":"Maharashtra", "pincode":421601, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":1.0, "mobileNumber":9594234555, "annualTurnover":"", "serviceNames":"Solar", "logoName":"", "website":"www.jdenerbiz.in", "email":"snehahjondhle@jdenerbiz.in", "description":"We provide a range of solar energy solutions to residential, commercial and industrial customers. JD Enerbiz vertically integrated solution provider for Solar Rooftops, Solar Pump, Solar Street Light, Solar Water Heater, LED Lights, DC Fans for all small, medium and large-sized industries", "rankingScore":"", "rating":"", "estd":2022},
  {"objectId":"xdFCCjmwSK", "name":"Nirmik Enterprises", "gstNumber":"", "status":"", "addressLine1":"201 Karan plaza 1 Nr Rosary School Warje Pune", "addressLine2":"", "area":"Warje", "city":"Pune", "state":"Maharashtra", "pincode":411058, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":5.0, "mobileNumber":9370390412, "annualTurnover":"", "serviceNames":"Fire System", "logoName":"", "website":"", "email":"nirmikenterprises@gmail.com", "description":"We provide the firefighting related services including training and fire drill for residential society, commercial complex, Manufacturing comapnies, warehouses, Govt offices, IT Companies and many more", "rankingScore":"", "rating":"", "estd":2017},
  {"objectId":"XI1LtXOYLa", "name":"Munshi Uncle", "gstNumber":"", "status":"", "addressLine1":"Office No 205, 2nd Floor, Bahirat Patil Empire, Pink City Road, Wakad, Pune 57", "addressLine2":"", "area":"Wakad", "city":"Pune", "state":"Maharashtra", "pincode":411057, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":1.0, "mobileNumber":8411051000, "annualTurnover":"", "serviceNames":"Accounting Service", "logoName":"", "website":"www.munshiuncle.com", "email":"munshiuncle.pune@gmail.com", "description":"Munshi uncle started its operations in the year 2018 with a vision to help housing societies by providing Accounting & Audit Solutions and also to adapt & embrace the changing world in the field of I T Accounting\n\nWe have automated various process which saves time, cost, increases collaboration with Managing Committee and accuracy of data points. Today we have a team of professionals from Accounting & Audit streams. We have a team of Chartered Accountants, GDC&A’s, Tax experts & Multiple Executives to handle day to day accounting operations.", "rankingScore":"", "rating":"", "estd":2021},
  {"objectId":"760rT0akdU", "name":"Protective Commercial Pvt Ltd", "gstNumber":"", "status":"", "addressLine1":"Sno 30 , Shrikrushna park, flat no 9 vijayraj colony 60 feet road, PIMPLE GURAV , Pune 411061 Maharashtra India", "addressLine2":"", "area":"Pimple Gaurav", "city":"Pune", "state":"Maharashtra", "pincode":411061, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":5.0, "mobileNumber":7030267877, "annualTurnover":"", "serviceNames":"EPDM", "logoName":"", "website":"", "email":"protective.commercial@gmail.com", "description":"We provide services related to Playground equipments, EPDM Work, Sport Facility Work, Playground related work\nReachout to us to know more details", "rankingScore":"", "rating":"", "estd":2017},
  {"objectId":"DRzx5slSDh", "name":"Auto Power Gen systems Pvt Ltd ", "gstNumber":"", "status":"", "addressLine1":"Plot No. 4 A/ 2/ 10, S No. 12, Sinhagad Road, Nanded Phata, near Sawali Dhaba, Pune, Maharashtra 411041", "addressLine2":"", "area":"Sinhgad Road", "city":"Pune", "state":"Maharashtra", "pincode":411041, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":16.0, "mobileNumber":9372895661, "annualTurnover":"", "serviceNames":"DG Service", "logoName":"", "website":"www.autopowergensets.com", "email":"autopowerengg@autopowergensets.com", "description":"Auto Power Gen Systems Pvt. Ltd. has been established in 2000 . Basically we are experts in diesel generator AMC services, engine repairing, alternator rewinding, AMF panel services, generator synchronizing, erection and installation.\n\nWe also provide DG sets on Hire / Rental basis from 5 Kva to 1000 Kva.", "rankingScore":"", "rating":"", "estd":2006},
  {"objectId":"95TkbQQTv3", "name":"Ankit Gardening Services ", "gstNumber":"", "status":"", "addressLine1":"Anand Park,Vadgaon Sheri", "addressLine2":"", "area":"Vadgaon Sheri", "city":"Pune", "state":"Maharashtra", "pincode":411014, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":2.0, "mobileNumber":906528395, "annualTurnover":"", "serviceNames":"Gardening", "logoName":"", "website":"", "email":"as4782294@gmail.com", "description":"Ankit Gardening provides all types of services for Gardening, Landscaping & Kitchen gardening in Viman Nagar, Wadgaon Sheri, Kalyani Nagar, Wagholi & Kharadi Area", "rankingScore":"", "rating":"", "estd":2020},
  {"objectId":"DGhWvhypNX", "name":"BVG India Limited", "gstNumber":"", "status":"", "addressLine1":"4th Floor, Midas Tower, Hinjewadi Rajiv Gandhi Infotech Park ,Hinjewadi , Pune ", "addressLine2":"", "area":"Hinjewadi", "city":"Pune", "state":"Maharashtra", "pincode":411057, "createdAt":"", "pan":"", "displayId":"", "services":"", "priority":"", "fullAddress":"", "package":"basic", "verified":"Yes", "numberOfClients":"", "experience":29.0, "mobileNumber":7875556161, "annualTurnover":"", "serviceNames":"Housekeeping, Security", "logoName":"", "website":"https://www.bvgindia.com/", "email":"info@cbvgindia.com", "description":"At BVG India, we take our commitments seriously and work towards delivering the value our clients, stakeholders, and society expects from us. Our technical expertise across various domains, including environment, waste management, facility management, etc., and our objective and vision to contribute to a sustainable future\n\nOur founder, Mr. Hanmantrao Ramdas Gaikwad, is a visionary Indian citizen who has immense faith and confidence in his team’s capabilities.", "rankingScore":"", "rating":"", "estd":1993}
  ];

  let fields = {
    "name": "name",  
    "estd": "estd",
    "gstNumber": "gstNumber",
    "pan": "pan",
    "package": "package",
    "verified": "verified",
    "experience": "experience",
    "mobileNumber": "mobileNumber",
    "website": "website",
    "email": "email",
    "description": "description"
  };

  for(let i = 0; i < rows.length; i++) {
    let row = rows[i];
    //console.log(row)
    let Partner = Parse.Object.extend('Partner');
    //console.log(row.objectId)
    let query =  new Parse.Query(Partner);
    try {
      if(row.objectId) {
        //console.log("Finding: "+row.objectId)
        let partner = await query.get(row.objectId,{useMasterKey: true});
        console.log("Partner Found for ObjectID: "+row.objectId);
        for (let key in fields) {
          console.log(`${key}, ${row[key]}`);
          if(row[key]) {
            //console.log(`${key}, ${row[key].trim()}`);
            partner.set(fields[key],row[key].toString());
          }
        }
        partner.set("numberOfClients",0);
        partner.set("verified",(row.verified == 'Yes'));
        partner.set("estd",Number(row.estd));
        partner.set("experience",Number(row.experience));
        partner.set("address",{
          addressLine1: row.addressLine1,
          addressLine2: row.addressLine2,
          area: row.area,
          city: row.city,
          state: row.state,
          pincode: row.pincode,
        });
        await partner.save(null,{useMasterKey: true});
      }
    } catch(e) {
      console.log("****************************");
      console.log(row.name);
      console.log(e.message);
      console.log("****************************");
    }
  }
}
